datasources:
  default:
    dialect: postgres
    url: jdbc:postgresql://localhost:5432/dev_identity
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'